"""Tests for the C89 code emitter."""

import pytest

from amipython.parse import parse
from amipython.typecheck import typecheck
from amipython.emit import emit


def _emit(source: str) -> str:
    tree = parse(source)
    info = typecheck(tree)
    return emit(tree, info)


class TestVariables:
    def test_int_assignment(self):
        c = _emit("x: int = 42")
        assert "LONG x;" in c
        assert "x = 42;" in c

    def test_float_assignment(self):
        c = _emit("x: float = 3.14")
        assert "float x;" in c
        assert "x = 3.14f;" in c

    def test_str_assignment(self):
        c = _emit('x: str = "hello"')
        assert "const char *x;" in c
        assert 'x = "hello";' in c

    def test_bool_assignment(self):
        c = _emit("x: bool = True")
        assert "BOOL x;" in c
        assert "x = TRUE;" in c


class TestArithmetic:
    def test_addition(self):
        c = _emit("x = 1 + 2")
        assert "(1 + 2)" in c

    def test_division_casts_to_float(self):
        c = _emit("x: int = 1\ny = x / 2")
        assert "(float)(x) / (float)(2)" in c

    def test_floor_division(self):
        c = _emit("x = 10 // 3")
        assert "amipython_floordiv(10, 3)" in c

    def test_modulo(self):
        c = _emit("x = 10 % 3")
        assert "amipython_mod(10, 3)" in c

    def test_power(self):
        c = _emit("x = 2 ** 3")
        assert "amipython_ipow(2, 3)" in c


class TestPrint:
    def test_simple_print(self):
        c = _emit('print("hello")')
        assert 'amipython_print_str("hello");' in c
        assert "amipython_print_newline();" in c

    def test_print_int(self):
        c = _emit("x: int = 42\nprint(x)")
        assert "amipython_print_long(x);" in c

    def test_print_multiple_args(self):
        c = _emit('x: int = 1\nprint("x =", x)')
        assert "amipython_print_space();" in c

    def test_print_no_args(self):
        c = _emit("print()")
        assert "amipython_print_newline();" in c


class TestControlFlow:
    def test_if_else(self):
        c = _emit("x: int = 1\nif x > 0:\n    pass\nelse:\n    pass")
        assert "if ((x > 0))" in c
        assert "} else {" in c

    def test_elif(self):
        c = _emit("x: int = 1\nif x > 0:\n    pass\nelif x == 0:\n    pass")
        assert "} else if ((x == 0))" in c

    def test_while(self):
        c = _emit("x: int = 1\nwhile x > 0:\n    x = x - 1")
        assert "while ((x > 0))" in c

    def test_for_range_one_arg(self):
        c = _emit("for i in range(5):\n    pass")
        assert "for (i = 0; i < 5; i++)" in c

    def test_for_range_two_args(self):
        c = _emit("for i in range(2, 10):\n    pass")
        assert "for (i = 2; i < 10; i++)" in c

    def test_for_range_three_args(self):
        c = _emit("for i in range(0, 10, 2):\n    pass")
        assert "i += 2)" in c

    def test_break(self):
        c = _emit("for i in range(5):\n    break")
        assert "break;" in c

    def test_continue(self):
        c = _emit("for i in range(5):\n    continue")
        assert "continue;" in c


class TestFunctions:
    def test_function_declaration(self):
        c = _emit("def add(a: int, b: int) -> int:\n    return a + b")
        assert "LONG add(LONG a, LONG b);" in c
        assert "LONG add(LONG a, LONG b) {" in c
        assert "return (a + b);" in c

    def test_void_function(self):
        c = _emit('def greet() -> int:\n    return 0')
        # Check forward declaration
        assert "LONG greet(void);" in c

    def test_function_call(self):
        c = _emit("def f(x: int) -> int:\n    return x\ny = f(42)")
        assert "f(42)" in c

    def test_function_locals_at_top(self):
        c = _emit(
            "def f(x: int) -> int:\n    y = x + 1\n    return y"
        )
        # Local y should be declared at top of function body
        lines = c.split("\n")
        func_start = next(i for i, l in enumerate(lines) if "LONG f(LONG x) {" in l)
        # Next non-empty line should be the local declaration
        decl_line = lines[func_start + 1].strip()
        assert decl_line == "LONG y;"


class TestBooleanOps:
    def test_and(self):
        c = _emit("x: bool = True and False")
        assert "&&" in c

    def test_or(self):
        c = _emit("x: bool = True or False")
        assert "||" in c

    def test_not(self):
        c = _emit("x: bool = not True")
        assert "!(TRUE)" in c


class TestStructure:
    def test_includes_header(self):
        c = _emit("x: int = 1")
        assert '#include "amipython.h"' in c

    def test_generated_comment(self):
        c = _emit("x: int = 1")
        assert "/* Generated by amipython */" in c

    def test_main_returns_zero(self):
        c = _emit("x: int = 1")
        assert "return 0;" in c
        assert "int main(void)" in c


STRUCT_PREAMBLE = "from dataclasses import dataclass\n"


class TestStruct:
    def test_struct_typedef(self):
        src = STRUCT_PREAMBLE + "@dataclass\nclass Ball:\n    x: float\n    y: float\n"
        c = _emit(src)
        assert "typedef struct {" in c
        assert "float x;" in c
        assert "float y;" in c
        assert "} Ball;" in c

    def test_struct_init(self):
        src = STRUCT_PREAMBLE + "@dataclass\nclass Ball:\n    x: float\n    y: float\nb = Ball(x=1.0, y=2.0)\n"
        c = _emit(src)
        assert "Ball b;" in c
        assert "b.x = 1.0f;" in c
        assert "b.y = 2.0f;" in c

    def test_struct_field_access(self):
        src = STRUCT_PREAMBLE + "@dataclass\nclass Ball:\n    x: float\nb = Ball(x=1.0)\nv = b.x\n"
        c = _emit(src)
        assert "v = b.x;" in c

    def test_struct_field_assign(self):
        src = STRUCT_PREAMBLE + "@dataclass\nclass Ball:\n    x: float\nb = Ball(x=1.0)\nb.x = 3.0\n"
        c = _emit(src)
        assert "b.x = 3.0f;" in c

    def test_struct_field_aug_assign(self):
        src = STRUCT_PREAMBLE + "@dataclass\nclass Ball:\n    x: float\nb = Ball(x=1.0)\nb.x += 0.5\n"
        c = _emit(src)
        assert "b.x += 0.5f;" in c

    def test_struct_default_field(self):
        src = STRUCT_PREAMBLE + "@dataclass\nclass Ball:\n    x: float\n    speed: float = 1.0\nb = Ball(x=5.0)\n"
        c = _emit(src)
        assert "b.x = 5.0f;" in c
        assert "b.speed = 1.0f;" in c


class TestList:
    def test_list_decl(self):
        src = STRUCT_PREAMBLE + "@dataclass\nclass Ball:\n    x: float\nballs: list[Ball] = []\n"
        c = _emit(src)
        assert "Ball balls_items[256];" in c
        assert "LONG balls_count = 0;" in c

    def test_list_int_decl(self):
        src = "nums: list[int] = []\n"
        c = _emit(src)
        assert "LONG nums_items[256];" in c
        assert "LONG nums_count = 0;" in c

    def test_list_append_struct(self):
        src = STRUCT_PREAMBLE + (
            "@dataclass\nclass Ball:\n    x: float\nballs: list[Ball] = []\n"
            "balls.append(Ball(x=1.0))\n"
        )
        c = _emit(src)
        assert "balls_items[balls_count].x = 1.0f;" in c
        assert "balls_count++;" in c

    def test_list_len(self):
        src = "nums: list[int] = []\nn = len(nums)\n"
        c = _emit(src)
        assert "n = nums_count;" in c

    def test_list_for_struct(self):
        src = STRUCT_PREAMBLE + (
            "@dataclass\nclass Ball:\n    x: float\nballs: list[Ball] = []\n"
            "def update():\n    for b in balls:\n        b.x += 1.0\n"
        )
        c = _emit(src)
        assert "for (b_idx = 0; b_idx < balls_count; b_idx++)" in c
        assert "b = &balls_items[b_idx];" in c
        assert "b->x += 1.0f;" in c

    def test_list_subscript_assign_int(self):
        src = "nums: list[int] = []\nnums.append(0)\nnums[0] = 42\n"
        c = _emit(src)
        assert "nums_items[0] = 42;" in c

    def test_list_subscript_assign_expr_index(self):
        src = (
            "board: list[int] = []\n"
            "for i in range(10):\n    board.append(0)\n"
            "x: int = 3\ny: int = 2\n"
            "board[y * 10 + x] = 1\n"
        )
        c = _emit(src)
        assert "board_items[((y * 10) + x)] = 1;" in c


class TestByRefParams:
    def test_struct_param_pointer_signature_and_call(self):
        c = _emit(STRUCT_PREAMBLE + (
            "@dataclass\nclass Merc:\n    hp: int\n"
            "def hurt(m: Merc, n: int):\n    m.hp -= n\n"
            "m = Merc(hp=10)\nhurt(m, 3)\n"
        ))
        assert "void hurt(Merc *m, LONG n);" in c
        assert "m->hp -= n;" in c
        assert "hurt(&m, 3);" in c

    def test_loop_ref_and_list_element_args(self):
        c = _emit(STRUCT_PREAMBLE + (
            "@dataclass\nclass Merc:\n    hp: int\n"
            "def hurt(m: Merc):\n    m.hp -= 1\n"
            "mercs: list[Merc] = []\nmercs.append(Merc(hp=5))\nhurt(mercs[0])\n"
            "def tick():\n    for m in mercs:\n        hurt(m)\n"
        ))
        assert "hurt(&mercs_items[0]);" in c
        assert "hurt(m);" in c          # loop var is already a pointer

    def test_engine_object_param(self):
        c = _emit(
            "from amiga import Display, Bitmap, Shape\n"
            "display = Display(320, 200)\nbm = Bitmap(320, 200)\n"
            "bm.box_filled(0, 0, 15, 15, 1)\ns = Shape.grab(bm, 0, 0, 16, 16)\n"
            "def draw(d: Display, sh: Shape, x: int):\n    d.blit(sh, x, 10)\n"
            "def wipe(b: Bitmap):\n    b.clear()\n"
            "draw(display, s, 5)\nwipe(bm)\n"
        )
        assert "void draw(AmipyDisplay *d, AmipyShape *sh, LONG x)" in c
        assert "amipython_display_blit(d, sh, x, 10);" in c
        assert "void wipe(AmipyBitmap *b)" in c
        assert "amipython_bitmap_clear(b);" in c
        assert "draw(&display, &s, 5);" in c
        assert "wipe(&bm);" in c

    def test_shape_loop_ref_passed_to_blit(self):
        c = _emit(
            "from amiga import Display, Bitmap, Shape\n"
            "display = Display(320, 200)\nbm = Bitmap(320, 200)\n"
            "shapes: list[Shape] = []\nshapes.append(Shape.grab(bm, 0, 0, 16, 16))\n"
            "for s in shapes:\n    display.blit(s, 1, 2)\n"
        )
        assert "amipython_display_blit(&display, s, 1, 2);" in c


class TestSizedListLiteral:
    def test_global_fill_and_capacity(self):
        c = _emit("W: int = 4\nH: int = 3\ngrid: list[int] = [0] * (W * H)\ngrid[5] = 2\n")
        assert "LONG grid_items[256];" in c   # capacity never shrinks below default
        assert "for (_fi = 0; _fi < 12; _fi++) grid_items[_fi] = 0;" in c
        assert "grid_count = 12;" in c

    def test_large_capacity(self):
        c = _emit("grid: list[int] = [0] * 1280\n")
        assert "LONG grid_items[1280];" in c
        assert "grid_count = 1280;" in c

    def test_str_and_bool_and_float_fills(self):
        c = _emit('names: list[str] = [""] * 4\nseen = [False] * 4\nws = [1.5] * 2\n')
        assert 'names_items[_fi] = "";' in c
        assert "seen_items[_fi] = FALSE;" in c
        assert "ws_items[_fi] = 1.5f;" in c

    def test_reassign_inside_function(self):
        c = _emit("grid: list[int] = [0] * 8\ndef reset():\n    global grid\n    grid = [7] * 8\n")
        assert "grid_items[_fi] = 7;" in c


class TestDisplayBlock:
    def test_block_emits_display_block(self):
        c = _emit(
            "from amiga import Display, Bitmap, Shape\n"
            "display = Display(320, 256)\nbm = Bitmap(320, 256)\n"
            "s = Shape.grab(bm, 0, 0, 16, 16)\n"
            "display.blit(s, 1, 2)\ndisplay.block(s, 3, 4)\n"
        )
        assert "amipython_display_blit(&display, &s, 1, 2);" in c
        assert "amipython_display_block(&display, &s, 3, 4);" in c

    def test_negative_fill(self):
        c = _emit("drawn: list[int] = [-1] * 4\n")
        assert "drawn_items[_fi] = -1;" in c
        assert "drawn_count = 4;" in c


class TestListElementFieldAssign:
    def test_emits_items_index_field(self):
        c = _emit(STRUCT_PREAMBLE + (
            "@dataclass\nclass Merc:\n    hp: int\n"
            "mercs: list[Merc] = []\nmercs.append(Merc(hp=5))\n"
            "mercs[0].hp = 7\nmercs[0].hp -= 2\n"
        ))
        assert "mercs_items[0].hp = 7;" in c
        assert "mercs_items[0].hp -= 2;" in c


class TestStorageListExpression:
    def test_load_int_list_in_expression_position(self):
        c = _emit(
            "from amiga import storage\n"
            "blob: list[int] = [0] * 300\n"
            "def load() -> bool:\n"
            "    if not storage.load_int_list(\"save\", blob):\n"
            "        return False\n"
            "    return True\n"
            "ok: bool = storage.load_int_list(\"save\", blob)\n"
            "storage.save_int_list(\"save\", blob)\n"
        )
        assert 'amipython_storage_load_int_list("save", blob_items, &blob_count, 300)' in c
        assert 'amipython_storage_save_int_list("save", blob_items, blob_count);' in c
        assert c.count("blob_items, &blob_count, 300") == 2



class TestBitmapFont:
    def test_font_call_emits_runtime_setter(self):
        c = _emit("from amiga import Bitmap\nbm = Bitmap(320, 200)\nbm.font(6)\nbm.print_at(1, 1, \"HI\")\nbm.font(8)\n")
        assert "amipython_bitmap_font(&bm, 6);" in c
        assert "amipython_bitmap_font(&bm, 8);" in c
