"""Tests for the C89 code emitter."""

import pytest

from amipython.parse import parse
from amipython.typecheck import typecheck
from amipython.emit import emit


def _emit(source: str) -> str:
    tree = parse(source)
    info = typecheck(tree)
    return emit(tree, info)


class TestVariables:
    def test_int_assignment(self):
        c = _emit("x: int = 42")
        assert "LONG x;" in c
        assert "x = 42;" in c

    def test_float_assignment(self):
        c = _emit("x: float = 3.14")
        assert "float x;" in c
        assert "x = 3.14f;" in c

    def test_str_assignment(self):
        c = _emit('x: str = "hello"')
        assert "const char *x;" in c
        assert 'x = "hello";' in c

    def test_bool_assignment(self):
        c = _emit("x: bool = True")
        assert "BOOL x;" in c
        assert "x = TRUE;" in c


class TestArithmetic:
    def test_addition(self):
        c = _emit("x = 1 + 2")
        assert "(1 + 2)" in c

    def test_division_casts_to_float(self):
        c = _emit("x: int = 1\ny = x / 2")
        assert "(float)(x) / (float)(2)" in c

    def test_floor_division(self):
        c = _emit("x = 10 // 3")
        assert "amipython_floordiv(10, 3)" in c

    def test_modulo(self):
        c = _emit("x = 10 % 3")
        assert "amipython_mod(10, 3)" in c

    def test_power(self):
        c = _emit("x = 2 ** 3")
        assert "amipython_ipow(2, 3)" in c


class TestPrint:
    def test_simple_print(self):
        c = _emit('print("hello")')
        assert 'amipython_print_str("hello");' in c
        assert "amipython_print_newline();" in c

    def test_print_int(self):
        c = _emit("x: int = 42\nprint(x)")
        assert "amipython_print_long(x);" in c

    def test_print_multiple_args(self):
        c = _emit('x: int = 1\nprint("x =", x)')
        assert "amipython_print_space();" in c

    def test_print_no_args(self):
        c = _emit("print()")
        assert "amipython_print_newline();" in c


class TestControlFlow:
    def test_if_else(self):
        c = _emit("x: int = 1\nif x > 0:\n    pass\nelse:\n    pass")
        assert "if ((x > 0))" in c
        assert "} else {" in c

    def test_elif(self):
        c = _emit("x: int = 1\nif x > 0:\n    pass\nelif x == 0:\n    pass")
        assert "} else if ((x == 0))" in c

    def test_while(self):
        c = _emit("x: int = 1\nwhile x > 0:\n    x = x - 1")
        assert "while ((x > 0))" in c

    def test_for_range_one_arg(self):
        c = _emit("for i in range(5):\n    pass")
        assert "for (i = 0; i < 5; i++)" in c

    def test_for_range_two_args(self):
        c = _emit("for i in range(2, 10):\n    pass")
        assert "for (i = 2; i < 10; i++)" in c

    def test_for_range_three_args(self):
        c = _emit("for i in range(0, 10, 2):\n    pass")
        assert "i += 2)" in c

    def test_break(self):
        c = _emit("for i in range(5):\n    break")
        assert "break;" in c

    def test_continue(self):
        c = _emit("for i in range(5):\n    continue")
        assert "continue;" in c


class TestFunctions:
    def test_function_declaration(self):
        c = _emit("def add(a: int, b: int) -> int:\n    return a + b")
        assert "LONG add(LONG a, LONG b);" in c
        assert "LONG add(LONG a, LONG b) {" in c
        assert "return (a + b);" in c

    def test_void_function(self):
        c = _emit('def greet() -> int:\n    return 0')
        # Check forward declaration
        assert "LONG greet(void);" in c

    def test_function_call(self):
        c = _emit("def f(x: int) -> int:\n    return x\ny = f(42)")
        assert "f(42)" in c

    def test_function_locals_at_top(self):
        c = _emit(
            "def f(x: int) -> int:\n    y = x + 1\n    return y"
        )
        # Local y should be declared at top of function body
        lines = c.split("\n")
        func_start = next(i for i, l in enumerate(lines) if "LONG f(LONG x) {" in l)
        # Next non-empty line should be the local declaration
        decl_line = lines[func_start + 1].strip()
        assert decl_line == "LONG y;"


class TestBooleanOps:
    def test_and(self):
        c = _emit("x: bool = True and False")
        assert "&&" in c

    def test_or(self):
        c = _emit("x: bool = True or False")
        assert "||" in c

    def test_not(self):
        c = _emit("x: bool = not True")
        assert "!(TRUE)" in c


class TestStructure:
    def test_includes_header(self):
        c = _emit("x: int = 1")
        assert '#include "amipython.h"' in c

    def test_generated_comment(self):
        c = _emit("x: int = 1")
        assert "/* Generated by amipython */" in c

    def test_main_returns_zero(self):
        c = _emit("x: int = 1")
        assert "return 0;" in c
        assert "int main(void)" in c


STRUCT_PREAMBLE = "from dataclasses import dataclass\n"


class TestStruct:
    def test_struct_typedef(self):
        src = STRUCT_PREAMBLE + "@dataclass\nclass Ball:\n    x: float\n    y: float\n"
        c = _emit(src)
        assert "typedef struct {" in c
        assert "float x;" in c
        assert "float y;" in c
        assert "} Ball;" in c

    def test_struct_init(self):
        src = STRUCT_PREAMBLE + "@dataclass\nclass Ball:\n    x: float\n    y: float\nb = Ball(x=1.0, y=2.0)\n"
        c = _emit(src)
        assert "Ball b;" in c
        assert "b.x = 1.0f;" in c
        assert "b.y = 2.0f;" in c

    def test_struct_field_access(self):
        src = STRUCT_PREAMBLE + "@dataclass\nclass Ball:\n    x: float\nb = Ball(x=1.0)\nv = b.x\n"
        c = _emit(src)
        assert "v = b.x;" in c

    def test_struct_field_assign(self):
        src = STRUCT_PREAMBLE + "@dataclass\nclass Ball:\n    x: float\nb = Ball(x=1.0)\nb.x = 3.0\n"
        c = _emit(src)
        assert "b.x = 3.0f;" in c

    def test_struct_field_aug_assign(self):
        src = STRUCT_PREAMBLE + "@dataclass\nclass Ball:\n    x: float\nb = Ball(x=1.0)\nb.x += 0.5\n"
        c = _emit(src)
        assert "b.x += 0.5f;" in c

    def test_struct_default_field(self):
        src = STRUCT_PREAMBLE + "@dataclass\nclass Ball:\n    x: float\n    speed: float = 1.0\nb = Ball(x=5.0)\n"
        c = _emit(src)
        assert "b.x = 5.0f;" in c
        assert "b.speed = 1.0f;" in c


class TestList:
    def test_list_decl(self):
        src = STRUCT_PREAMBLE + "@dataclass\nclass Ball:\n    x: float\nballs: list[Ball] = []\n"
        c = _emit(src)
        assert "Ball balls_items[64];" in c
        assert "LONG balls_count = 0;" in c

    def test_list_int_decl(self):
        src = "nums: list[int] = []\n"
        c = _emit(src)
        assert "LONG nums_items[64];" in c
        assert "LONG nums_count = 0;" in c

    def test_list_append_struct(self):
        src = STRUCT_PREAMBLE + (
            "@dataclass\nclass Ball:\n    x: float\nballs: list[Ball] = []\n"
            "balls.append(Ball(x=1.0))\n"
        )
        c = _emit(src)
        assert "balls_items[balls_count].x = 1.0f;" in c
        assert "balls_count++;" in c

    def test_list_len(self):
        src = "nums: list[int] = []\nn = len(nums)\n"
        c = _emit(src)
        assert "n = nums_count;" in c

    def test_list_for_struct(self):
        src = STRUCT_PREAMBLE + (
            "@dataclass\nclass Ball:\n    x: float\nballs: list[Ball] = []\n"
            "def update():\n    for b in balls:\n        b.x += 1.0\n"
        )
        c = _emit(src)
        assert "for (b_idx = 0; b_idx < balls_count; b_idx++)" in c
        assert "b = &balls_items[b_idx];" in c
        assert "b->x += 1.0f;" in c
