"""C89 code emitter for the amipython transpiler."""

import ast

from amipython.engine import BUILTINS, MODULE_TYPES, OBJECT_TYPES
from amipython.errors import EmitError
from amipython.types import (
    C_TYPE_MAP,
    ENGINE_TYPE_MAP,
    FORMAT_MAP,
    AmipyType,
    TypeInfo,
    VariableInfo,
)


# Map AmipyType to the amipython_print_* function name
_PRINT_FN_MAP: dict[AmipyType, str] = {
    AmipyType.INT: "amipython_print_long",
    AmipyType.FLOAT: "amipython_print_float",
    AmipyType.BOOL: "amipython_print_bool",
    AmipyType.STR: "amipython_print_str",
}


def emit(tree: ast.Module, info: TypeInfo) -> str:
    """Emit C89 code from a type-checked AST."""
    emitter = _Emitter(info)
    return emitter.emit_module(tree)


class _Emitter:
    def __init__(self, info: TypeInfo):
        self.info = info
        self.indent = 0
        self.lines: list[str] = []

    def _line(self, text: str = ""):
        if text:
            self.lines.append("    " * self.indent + text)
        else:
            self.lines.append("")

    def _type_str(self, t: AmipyType) -> str:
        return C_TYPE_MAP[t]

    def _var_decl(self, t: AmipyType, name: str) -> str:
        """Format a variable declaration, handling pointer types correctly."""
        c_type = C_TYPE_MAP[t]
        if c_type.endswith("*"):
            return f"{c_type}{name}"
        return f"{c_type} {name}"

    def _format_spec(self, t: AmipyType) -> str:
        return FORMAT_MAP[t]

    def _expr_type(self, node: ast.expr) -> AmipyType:
        t = self.info.expr_types.get(id(node))
        if t is None:
            raise EmitError(
                f"no type info for expression",
                lineno=getattr(node, "lineno", None),
            )
        return t

    def _uses_float(self) -> bool:
        """Check if the program uses any float types."""
        for var in self.info.globals.values():
            if var.type == AmipyType.FLOAT:
                return True
        for func in self.info.functions.values():
            if func.return_type == AmipyType.FLOAT:
                return True
            for param in func.params:
                if param.type == AmipyType.FLOAT:
                    return True
        for locals_dict in self.info.locals.values():
            for var in locals_dict.values():
                if var.type == AmipyType.FLOAT:
                    return True
        for t in self.info.expr_types.values():
            if t == AmipyType.FLOAT:
                return True
        return False

    def emit_module(self, tree: ast.Module) -> str:
        self.lines = []
        self._line("/* Generated by amipython */")
        if self._uses_float():
            self._line("#define AMIPYTHON_USE_FLOAT")
        self._line('#include "amipython.h"')
        if self.info.engine_imports:
            self._line('#include "amipython_engine.h"')
        self._line()

        # Collect function declarations (forward declarations)
        functions = [n for n in tree.body if isinstance(n, ast.FunctionDef)]
        for func_node in functions:
            self._emit_forward_decl(func_node)

        if functions:
            self._line()

        # Emit global variable declarations
        self._emit_global_declarations(tree)

        # Emit function definitions
        for func_node in functions:
            self._emit_function(func_node)

        # Emit main
        self._emit_main(tree)

        return "\n".join(self.lines) + "\n"

    def _emit_forward_decl(self, node: ast.FunctionDef):
        func = self.info.functions[node.name]
        params = ", ".join(
            self._var_decl(p.type, p.name) for p in func.params
        )
        if not params:
            params = "void"
        self._line(f"{self._type_str(func.return_type)} {node.name}({params});")

    def _emit_global_declarations(self, tree: ast.Module):
        """Emit global variable declarations."""
        declared = set()
        for name, var in self.info.globals.items():
            if var.type == AmipyType.MODULE:
                continue  # modules aren't C variables
            self._line(f"{self._var_decl(var.type, name)};")
            declared.add(name)
        if declared:
            self._line()

    def _emit_function(self, node: ast.FunctionDef):
        func = self.info.functions[node.name]
        params = ", ".join(
            self._var_decl(p.type, p.name) for p in func.params
        )
        if not params:
            params = "void"
        self._line(f"{self._type_str(func.return_type)} {node.name}({params}) {{")
        self.indent += 1

        # Declare local variables at top of scope (C89)
        locals_dict = self.info.locals.get(node.name, {})
        param_names = {p.name for p in func.params}
        local_vars = {
            k: v for k, v in locals_dict.items() if k not in param_names
        }
        for var_name, var_info in local_vars.items():
            self._line(f"{self._var_decl(var_info.type, var_name)};")
        if local_vars:
            self._line()

        # Emit function body (skip Global statements)
        for stmt in node.body:
            if not isinstance(stmt, ast.Global):
                self._emit_stmt(stmt)

        self.indent -= 1
        self._line("}")
        self._line()

    def _emit_main(self, tree: ast.Module):
        """Emit the main function from module-level statements."""
        has_engine = bool(self.info.engine_imports)
        # Collect module-level statements (non-function-defs, non-imports)
        stmts = [n for n in tree.body
                 if not isinstance(n, (ast.FunctionDef, ast.ImportFrom))]
        if not stmts:
            self._line("int main(void) {")
            self.indent += 1
            if has_engine:
                self._line("amipython_engine_create();")
                self._line("amipython_engine_destroy();")
            self._line("return 0;")
            self.indent -= 1
            self._line("}")
            return

        self._line("int main(void) {")
        self.indent += 1

        if has_engine:
            self._line("amipython_engine_create();")

        for stmt in stmts:
            self._emit_stmt(stmt)

        if has_engine:
            self._line("amipython_engine_destroy();")
        self._line("return 0;")
        self.indent -= 1
        self._line("}")

    def _emit_stmt(self, node: ast.stmt):
        if isinstance(node, ast.Assign):
            self._emit_assign(node)
        elif isinstance(node, ast.AnnAssign):
            self._emit_ann_assign(node)
        elif isinstance(node, ast.AugAssign):
            self._emit_aug_assign(node)
        elif isinstance(node, ast.Expr):
            self._emit_expr_stmt(node)
        elif isinstance(node, ast.If):
            self._emit_if(node)
        elif isinstance(node, ast.While):
            self._emit_while(node)
        elif isinstance(node, ast.For):
            self._emit_for(node)
        elif isinstance(node, ast.Return):
            self._emit_return(node)
        elif isinstance(node, ast.Break):
            self._line("break;")
        elif isinstance(node, ast.Continue):
            self._line("continue;")
        elif isinstance(node, ast.Pass):
            pass  # No C output needed
        elif isinstance(node, ast.Global):
            pass  # Handled by type checker
        elif isinstance(node, ast.ImportFrom):
            pass  # Handled at module level
        else:
            raise EmitError(
                f"unsupported statement: {type(node).__name__}",
                lineno=getattr(node, "lineno", None),
            )

    def _emit_assign(self, node: ast.Assign):
        target = node.targets[0]
        if isinstance(target, ast.Name):
            # Engine constructor: display = Display(320, 256, bitplanes=8)
            if (isinstance(node.value, ast.Call)
                    and isinstance(node.value.func, ast.Name)
                    and node.value.func.id in OBJECT_TYPES
                    and node.value.func.id in self.info.engine_imports):
                self._emit_engine_init(target.id, node.value)
                return
            val = self._emit_expr(node.value)
            self._line(f"{target.id} = {val};")

    def _emit_ann_assign(self, node: ast.AnnAssign):
        if isinstance(node.target, ast.Name) and node.value is not None:
            val = self._emit_expr(node.value)
            self._line(f"{node.target.id} = {val};")

    def _emit_aug_assign(self, node: ast.AugAssign):
        if isinstance(node.target, ast.Name):
            target = node.target.id
            op = self._binop_symbol(node.op)
            # For special operators, expand to full assignment
            if isinstance(node.op, (ast.FloorDiv, ast.Pow, ast.Mod)):
                var = self._get_var_info(node.target.id)
                left_expr = target
                right_expr = self._emit_expr(node.value)
                val = self._emit_binop_call(
                    node.op, left_expr, right_expr,
                    var.type if var else AmipyType.INT,
                    self._expr_type(node.value)
                )
                self._line(f"{target} = {val};")
            elif isinstance(node.op, ast.Div):
                right_expr = self._emit_expr(node.value)
                self._line(f"{target} = (float)({target}) / (float)({right_expr});")
            else:
                val = self._emit_expr(node.value)
                self._line(f"{target} {op}= {val};")

    def _emit_expr_stmt(self, node: ast.Expr):
        if isinstance(node.value, ast.Call):
            call = node.value
            if isinstance(call.func, ast.Name):
                if call.func.id == "print":
                    self._emit_print(call)
                    return
                # Engine builtin: wait_mouse(), vwait()
                if (call.func.id in BUILTINS
                        and call.func.id in self.info.engine_imports):
                    builtin = BUILTINS[call.func.id]
                    args = ", ".join(self._emit_expr(a) for a in call.args)
                    self._line(f"{builtin.c_name}({args});")
                    return
            # Method call: bm.circle_filled(...) or palette.aga(...)
            if isinstance(call.func, ast.Attribute):
                self._emit_method_call_stmt(call)
                return
        # General expression statement
        val = self._emit_expr(node.value)
        self._line(f"{val};")

    def _emit_print(self, node: ast.Call):
        """Emit print() using amipython_print_* helpers."""
        if not node.args:
            self._line("amipython_print_newline();")
            return

        for i, arg in enumerate(node.args):
            if i > 0:
                self._line("amipython_print_space();")
            arg_type = self._expr_type(arg)
            val = self._emit_expr(arg)
            print_fn = _PRINT_FN_MAP.get(arg_type)
            if print_fn:
                self._line(f"{print_fn}({val});")
            else:
                self._line(f"amipython_print_str({val});")
        self._line("amipython_print_newline();")

    def _emit_engine_init(self, var_name: str, call: ast.Call):
        """Emit engine constructor as init call: amipython_display_init(&d, ...)."""
        type_name = call.func.id
        obj_type = OBJECT_TYPES[type_name]
        ctor = obj_type.constructor

        # Build arg list: positional args + keyword args (fill defaults)
        args = [self._emit_expr(a) for a in call.args]
        kw_provided = {kw.arg: self._emit_expr(kw.value) for kw in call.keywords}
        for kw_name, (kw_type, kw_default) in ctor.keywords.items():
            if kw_name in kw_provided:
                args.append(kw_provided[kw_name])
            else:
                args.append(str(kw_default))

        all_args = f"&{var_name}, " + ", ".join(args) if args else f"&{var_name}"
        self._line(f"{obj_type.c_init}({all_args});")

    def _emit_method_call_stmt(self, call: ast.Call):
        """Emit method/module function call as statement."""
        attr = call.func
        if not isinstance(attr.value, ast.Name):
            raise EmitError("unsupported method call", lineno=call.lineno)

        obj_name = attr.value.id
        method_name = attr.attr
        args_strs = [self._emit_arg(a) for a in call.args]

        # Module function: palette.aga(...)
        if obj_name in self.info.engine_modules:
            mod = MODULE_TYPES[obj_name]
            func = mod.functions[method_name]
            args = ", ".join(args_strs)
            self._line(f"{func.c_name}({args});")
            return

        # Object method: bm.circle_filled(...)
        var = self._get_var_info(obj_name)
        if var is None:
            raise EmitError(f"unknown variable '{obj_name}'", lineno=call.lineno)

        obj_type_info = None
        for ot in OBJECT_TYPES.values():
            if ENGINE_TYPE_MAP.get(ot.python_name) == var.type:
                obj_type_info = ot
                break
        if obj_type_info is None:
            raise EmitError(
                f"'{obj_name}' is not an engine object", lineno=call.lineno
            )

        method = obj_type_info.methods[method_name]
        args = ", ".join(args_strs)
        if args:
            self._line(f"{method.c_name}(&{obj_name}, {args});")
        else:
            self._line(f"{method.c_name}(&{obj_name});")

    def _emit_if(self, node: ast.If):
        cond = self._emit_expr(node.test)
        self._line(f"if ({cond}) {{")
        self.indent += 1
        for stmt in node.body:
            self._emit_stmt(stmt)
        self.indent -= 1

        if node.orelse:
            if len(node.orelse) == 1 and isinstance(node.orelse[0], ast.If):
                # elif
                elif_node = node.orelse[0]
                cond = self._emit_expr(elif_node.test)
                self._line(f"}} else if ({cond}) {{")
                self.indent += 1
                for stmt in elif_node.body:
                    self._emit_stmt(stmt)
                self.indent -= 1
                if elif_node.orelse:
                    self._emit_else(elif_node.orelse)
                else:
                    self._line("}")
            else:
                self._emit_else(node.orelse)
        else:
            self._line("}")

    def _emit_else(self, orelse: list[ast.stmt]):
        if len(orelse) == 1 and isinstance(orelse[0], ast.If):
            elif_node = orelse[0]
            cond = self._emit_expr(elif_node.test)
            self._line(f"}} else if ({cond}) {{")
            self.indent += 1
            for stmt in elif_node.body:
                self._emit_stmt(stmt)
            self.indent -= 1
            if elif_node.orelse:
                self._emit_else(elif_node.orelse)
            else:
                self._line("}")
        else:
            self._line("} else {")
            self.indent += 1
            for stmt in orelse:
                self._emit_stmt(stmt)
            self.indent -= 1
            self._line("}")

    def _emit_while(self, node: ast.While):
        cond = self._emit_expr(node.test)
        self._line(f"while ({cond}) {{")
        self.indent += 1
        for stmt in node.body:
            self._emit_stmt(stmt)
        self.indent -= 1
        self._line("}")

    def _emit_for(self, node: ast.For):
        """Emit `for i in range(...)` as a C for loop."""
        if not isinstance(node.target, ast.Name):
            raise EmitError("for loop target must be a name", lineno=node.lineno)
        var = node.target.id
        args = node.iter.args if isinstance(node.iter, ast.Call) else []

        if len(args) == 1:
            end = self._emit_expr(args[0])
            self._line(f"for ({var} = 0; {var} < {end}; {var}++) {{")
        elif len(args) == 2:
            start = self._emit_expr(args[0])
            end = self._emit_expr(args[1])
            self._line(f"for ({var} = {start}; {var} < {end}; {var}++) {{")
        elif len(args) == 3:
            start = self._emit_expr(args[0])
            end = self._emit_expr(args[1])
            step = self._emit_expr(args[2])
            # Need to handle negative steps
            self._line(
                f"for ({var} = {start}; "
                f"({step}) > 0 ? {var} < {end} : {var} > {end}; "
                f"{var} += {step}) {{"
            )
        else:
            raise EmitError("range() requires 1-3 arguments", lineno=node.lineno)

        self.indent += 1
        for stmt in node.body:
            self._emit_stmt(stmt)
        self.indent -= 1
        self._line("}")

    def _emit_return(self, node: ast.Return):
        if node.value is None:
            self._line("return;")
        else:
            val = self._emit_expr(node.value)
            self._line(f"return {val};")

    def _emit_expr(self, node: ast.expr) -> str:
        """Emit an expression and return the C code string."""
        if isinstance(node, ast.Constant):
            return self._emit_constant(node)
        if isinstance(node, ast.Name):
            return node.id
        if isinstance(node, ast.BinOp):
            return self._emit_binop(node)
        if isinstance(node, ast.UnaryOp):
            return self._emit_unaryop(node)
        if isinstance(node, ast.BoolOp):
            return self._emit_boolop(node)
        if isinstance(node, ast.Compare):
            return self._emit_compare(node)
        if isinstance(node, ast.Call):
            return self._emit_call(node)
        raise EmitError(
            f"unsupported expression: {type(node).__name__}",
            lineno=getattr(node, "lineno", None),
        )

    def _emit_constant(self, node: ast.Constant) -> str:
        if isinstance(node.value, bool):
            return "TRUE" if node.value else "FALSE"
        if isinstance(node.value, int):
            return str(node.value)
        if isinstance(node.value, float):
            # Ensure float literal has a decimal point
            s = repr(node.value)
            if "." not in s and "e" not in s and "E" not in s:
                s += ".0"
            # Add f suffix for C float
            return s + "f"
        if isinstance(node.value, str):
            # Escape the string for C
            escaped = (
                node.value.replace("\\", "\\\\")
                .replace('"', '\\"')
                .replace("\n", "\\n")
                .replace("\t", "\\t")
            )
            return f'"{escaped}"'
        raise EmitError(
            f"unsupported constant type: {type(node.value).__name__}",
            lineno=node.lineno,
        )

    def _emit_binop(self, node: ast.BinOp) -> str:
        left = self._emit_expr(node.left)
        right = self._emit_expr(node.right)
        left_type = self._expr_type(node.left)
        right_type = self._expr_type(node.right)

        # Division always yields float
        if isinstance(node.op, ast.Div):
            return f"(float)({left}) / (float)({right})"

        # Floor division, modulo, power — use helper functions
        if isinstance(node.op, (ast.FloorDiv, ast.Pow, ast.Mod)):
            return self._emit_binop_call(
                node.op, left, right, left_type, right_type
            )

        op = self._binop_symbol(node.op)
        return f"({left} {op} {right})"

    def _emit_binop_call(
        self,
        op: ast.operator,
        left: str,
        right: str,
        left_type: AmipyType,
        right_type: AmipyType,
    ) -> str:
        is_float = left_type == AmipyType.FLOAT or right_type == AmipyType.FLOAT

        if isinstance(op, ast.FloorDiv):
            if is_float:
                return f"amipython_floordiv_f({left}, {right})"
            return f"amipython_floordiv({left}, {right})"

        if isinstance(op, ast.Mod):
            if is_float:
                return f"amipython_mod_f({left}, {right})"
            return f"amipython_mod({left}, {right})"

        if isinstance(op, ast.Pow):
            if is_float:
                return f"amipython_fpow({left}, {right})"
            return f"amipython_ipow({left}, {right})"

        raise EmitError(f"unsupported operator: {type(op).__name__}")

    def _binop_symbol(self, op: ast.operator) -> str:
        ops = {
            ast.Add: "+",
            ast.Sub: "-",
            ast.Mult: "*",
            ast.Div: "/",
            ast.Mod: "%",
        }
        cls = type(op)
        if cls in ops:
            return ops[cls]
        raise EmitError(f"unsupported operator: {cls.__name__}")

    def _emit_unaryop(self, node: ast.UnaryOp) -> str:
        operand = self._emit_expr(node.operand)
        if isinstance(node.op, ast.Not):
            return f"!({operand})"
        if isinstance(node.op, ast.USub):
            return f"(-{operand})"
        if isinstance(node.op, ast.UAdd):
            return f"(+{operand})"
        raise EmitError(f"unsupported unary op: {type(node.op).__name__}")

    def _emit_boolop(self, node: ast.BoolOp) -> str:
        op = "&&" if isinstance(node.op, ast.And) else "||"
        parts = [self._emit_expr(v) for v in node.values]
        return f"({f' {op} '.join(parts)})"

    def _emit_compare(self, node: ast.Compare) -> str:
        parts = []
        left = self._emit_expr(node.left)
        for op, comparator in zip(node.ops, node.comparators):
            right = self._emit_expr(comparator)
            cmp_op = self._cmpop_symbol(op)
            parts.append(f"({left} {cmp_op} {right})")
            left = right
        if len(parts) == 1:
            return parts[0]
        return "(" + " && ".join(parts) + ")"

    def _cmpop_symbol(self, op: ast.cmpop) -> str:
        ops = {
            ast.Eq: "==",
            ast.NotEq: "!=",
            ast.Lt: "<",
            ast.LtE: "<=",
            ast.Gt: ">",
            ast.GtE: ">=",
        }
        cls = type(op)
        if cls in ops:
            return ops[cls]
        raise EmitError(f"unsupported comparison: {cls.__name__}")

    def _emit_call(self, node: ast.Call) -> str:
        if isinstance(node.func, ast.Name):
            name = node.func.id
            if name == "print":
                # print is handled at statement level
                return ""
            if name == "int":
                arg = self._emit_expr(node.args[0])
                return f"(LONG)({arg})"
            if name == "float":
                arg = self._emit_expr(node.args[0])
                return f"(float)({arg})"
            if name == "abs":
                arg = self._emit_expr(node.args[0])
                arg_type = self._expr_type(node.args[0])
                if arg_type == AmipyType.FLOAT:
                    return f"(({arg}) < 0.0f ? -({arg}) : ({arg}))"
                return f"(({arg}) < 0 ? -({arg}) : ({arg}))"
            # Engine builtin as expression
            if name in BUILTINS and name in self.info.engine_imports:
                builtin = BUILTINS[name]
                args = ", ".join(self._emit_expr(a) for a in node.args)
                return f"{builtin.c_name}({args})"
            # User function call
            args = ", ".join(self._emit_expr(a) for a in node.args)
            return f"{name}({args})"
        if isinstance(node.func, ast.Attribute):
            return self._emit_method_call_expr(node)
        raise EmitError("unsupported call expression", lineno=node.lineno)

    def _emit_method_call_expr(self, call: ast.Call) -> str:
        """Emit method/module function call as expression."""
        attr = call.func
        if not isinstance(attr.value, ast.Name):
            raise EmitError("unsupported method call", lineno=call.lineno)

        obj_name = attr.value.id
        method_name = attr.attr
        args_strs = [self._emit_arg(a) for a in call.args]

        if obj_name in self.info.engine_modules:
            mod = MODULE_TYPES[obj_name]
            func = mod.functions[method_name]
            args = ", ".join(args_strs)
            return f"{func.c_name}({args})"

        var = self._get_var_info(obj_name)
        if var is None:
            raise EmitError(f"unknown variable '{obj_name}'", lineno=call.lineno)

        obj_type_info = None
        for ot in OBJECT_TYPES.values():
            if ENGINE_TYPE_MAP.get(ot.python_name) == var.type:
                obj_type_info = ot
                break
        if obj_type_info is None:
            raise EmitError(
                f"'{obj_name}' is not an engine object", lineno=call.lineno
            )

        method = obj_type_info.methods[method_name]
        args = ", ".join(args_strs)
        if args:
            return f"{method.c_name}(&{obj_name}, {args})"
        return f"{method.c_name}(&{obj_name})"

    def _get_var_info(self, name: str) -> VariableInfo | None:
        if name in self.info.globals:
            return self.info.globals[name]
        return None

    def _is_engine_object_type(self, t: AmipyType) -> bool:
        return t in (AmipyType.DISPLAY, AmipyType.BITMAP)

    def _emit_arg(self, node: ast.expr) -> str:
        """Emit an argument, adding & for engine object references."""
        expr_str = self._emit_expr(node)
        t = self._expr_type(node)
        if self._is_engine_object_type(t):
            return f"&{expr_str}"
        return expr_str
