/* Generated by amipython */
#include "amipython.h"

LONG square(LONG n);

LONG x;
const char *name;
LONG i;

LONG square(LONG n) {
    return (n * n);
}

int main(void) {
    x = 42;
    name = "Amiga";
    amipython_print_str("Hello,");
    amipython_print_space();
    amipython_print_str(name);
    amipython_print_newline();
    amipython_print_str("square(x) =");
    amipython_print_space();
    amipython_print_long(square(x));
    amipython_print_newline();
    for (i = 0; i < 5; i++) {
        amipython_print_str("i =");
        amipython_print_space();
        amipython_print_long(i);
        amipython_print_newline();
    }
    return 0;
}
