#!/usr/bin/env python3
"""Regenerate the C runtime's s_font6x8 table from src/amiga/_font6.py.

    python scripts/gen_font6.py

Replaces the block between the FONT6_BEGIN / FONT6_END markers in
src/amipython/c_runtime/amipython_engine_amiga.c."""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
from amiga._font6 import FONT_6X8  # noqa: E402

C_FILE = ROOT / "src/amipython/c_runtime/amipython_engine_amiga.c"
BEGIN = "/* FONT6_BEGIN — generated by scripts/gen_font6.py, do not edit */"
END = "/* FONT6_END */"


def table() -> str:
    lines = [BEGIN,
             "/* 6x8 condensed font — 5x7 glyphs, column 5 and row 7 clear. Same",
             " * range as s_font8x8 (0x20..0x5A). Source: src/amiga/_font6.py */",
             "static const UBYTE s_font6x8[][8] = {"]
    for code in range(0x20, 0x5B):
        ch = chr(code)
        rows = FONT_6X8[ch]
        label = "'" + ("\\'" if ch == "'" else ch) + "'"
        lines.append(f"    /* 0x{code:02X} {label} */ {{{','.join(f'0x{b:02X}' for b in rows)}}},")
    lines.append("};")
    lines.append(END)
    return "\n".join(lines)


def main() -> None:
    src = C_FILE.read_text()
    new = table()
    if BEGIN in src:
        src = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda m: new, src, flags=re.S)
    else:
        anchor = "/* 8x8 bitmap font — printable ASCII subset (A-Z, 0-9, punctuation, space) */"
        assert anchor in src, "anchor for font tables not found"
        src = src.replace(anchor, new + "\n\n" + anchor, 1)
    C_FILE.write_text(src)
    print(f"wrote s_font6x8 ({0x5B - 0x20} glyphs) into {C_FILE.name}")


if __name__ == "__main__":
    main()
