/* Generated by amipython */
#define AMIPYTHON_USE_FLOAT
#include "amipython.h"

LONG a;
LONG b;
float c;
float d;

int main(void) {
    a = 10;
    b = 3;
    amipython_print_str("add =");
    amipython_print_space();
    amipython_print_long((a + b));
    amipython_print_newline();
    amipython_print_str("sub =");
    amipython_print_space();
    amipython_print_long((a - b));
    amipython_print_newline();
    amipython_print_str("mul =");
    amipython_print_space();
    amipython_print_long((a * b));
    amipython_print_newline();
    amipython_print_str("div =");
    amipython_print_space();
    amipython_print_float((float)(a) / (float)(b));
    amipython_print_newline();
    amipython_print_str("floordiv =");
    amipython_print_space();
    amipython_print_long(amipython_floordiv(a, b));
    amipython_print_newline();
    amipython_print_str("mod =");
    amipython_print_space();
    amipython_print_long(amipython_mod(a, b));
    amipython_print_newline();
    amipython_print_str("pow =");
    amipython_print_space();
    amipython_print_long(amipython_ipow(a, b));
    amipython_print_newline();
    c = 2.5f;
    d = 1.5f;
    amipython_print_str("fadd =");
    amipython_print_space();
    amipython_print_float((c + d));
    amipython_print_newline();
    amipython_print_str("fmul =");
    amipython_print_space();
    amipython_print_float((c * d));
    amipython_print_newline();
    return 0;
}
