/* Generated by amipython */
#include "amipython.h"

LONG x;
LONG total;
LONG i;
LONG count;
LONG j;

int main(void) {
    x = 10;
    if ((x > 5)) {
        amipython_print_str("big");
        amipython_print_newline();
    } else if ((x > 0)) {
        amipython_print_str("small");
        amipython_print_newline();
    } else {
        amipython_print_str("zero or negative");
        amipython_print_newline();
    }
    total = 0;
    i = 0;
    while ((i < 5)) {
        total = (total + i);
        i = (i + 1);
    }
    amipython_print_str("total =");
    amipython_print_space();
    amipython_print_long(total);
    amipython_print_newline();
    for (j = 0; j < 3; j++) {
        if ((j == 1)) {
            continue;
        }
        amipython_print_str("j =");
        amipython_print_space();
        amipython_print_long(j);
        amipython_print_newline();
    }
    count = 0;
    while (TRUE) {
        count = (count + 1);
        if ((count >= 3)) {
            break;
        }
    }
    amipython_print_str("count =");
    amipython_print_space();
    amipython_print_long(count);
    amipython_print_newline();
    return 0;
}
