/* Generated by amipython */
#include "amipython.h"
#include "amipython_engine.h"

AmipyDisplay display;
AmipyBitmap bm;
LONG i;

int main(void) {
    amipython_engine_create();
    amipython_display_init(&display, 320, 256, 8);
    amipython_bitmap_init(&bm, 320, 256, 8);
    for (i = 0; i < 256; i++) {
        amipython_palette_aga(i, i, i, i);
    }
    for (i = 255; ((-1)) > 0 ? i < 0 : i > 0; i += (-1)) {
        amipython_bitmap_circle_filled(&bm, 160, 128, amipython_floordiv(i, 2), i);
    }
    amipython_display_show(&display, &bm);
    amipython_wait_mouse();
    amipython_engine_destroy();
    return 0;
}
