/* Generated by amipython */
#include "amipython.h"

LONG add(LONG a, LONG b);
const char * greet(const char *name);
BOOL is_positive(LONG n);

LONG result;

LONG add(LONG a, LONG b) {
    return (a + b);
}

const char * greet(const char *name) {
    return name;
}

BOOL is_positive(LONG n) {
    return (n > 0);
}

int main(void) {
    result = add(3, 4);
    amipython_print_str("add =");
    amipython_print_space();
    amipython_print_long(result);
    amipython_print_newline();
    amipython_print_str("greet =");
    amipython_print_space();
    amipython_print_str(greet("world"));
    amipython_print_newline();
    amipython_print_str("positive =");
    amipython_print_space();
    amipython_print_bool(is_positive(5));
    amipython_print_newline();
    amipython_print_str("negative =");
    amipython_print_space();
    amipython_print_bool(is_positive((-1)));
    amipython_print_newline();
    return 0;
}
